# Generated by Django 3.0.5 on 2021-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Hatsun Agro Product Ltd', 'Hatsun Agro Product Ltd'), ('Jalkheri Power Private Limited JPPL', 'Jalkheri Power Private Limited JPPL'), ('MUNZER BHARAT Pvt Ltd', 'MUNZER BHARAT Pvt Ltd'), ('Grain Mart India', 'Grain Mart India'), ('Punjab State Power Corporation Limited', 'Punjab State Power Corporation Limited'), ('Dharma Productions', 'Dharma Productions')], default='Grain Mart India', max_length=50),
        ),
    ]
